- name: Update apt cache (apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600 # Don't update if we updated in the last hour

- name: Wait for automatic system updates to finish (Avoid apt lock)
  ansible.builtin.shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      echo "Waiting for apt lock..."
      sleep 5
    done
  changed_when: false
  failed_when: false


- name: Install packages (apt install ...)
  apt:
    name:
      - curl
      - git
      - htop
      - ufw
      - fail2ban
      - python3-pip
    state: present
  retries: 20
  delay: 10

- name: Install unattended upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Enable Unattended Upgrades for Security # apt update every 1 day, 
                                                # if you foud updates, install them every 1 day
                                                # apt autoclean every 7 days
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1"; 
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    mode: '0644'
