all:
  children:
    servers:
      hosts:
        server-vm:
          ansible_host: 10.69.10.5
          ansible_port: 22
    dmz:
      hosts:
        dmz-vm:
          ansible_host: 10.69.20.5
          ansible_port: 22
    gitlab:
      hosts:
        gitlab-server:
          ansible_host: 10.69.10.6
          ansible_port: 22
        gitlab-runner:
          ansible_host: 10.69.10.7
          ansible_port: 22

