
- name: Allow SSH in
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
    direction: in
  loop:
    - '{{ gitlab_ssh_port }}'


- name: Allow HTTP to the good port
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
    direction: in
  loop:
    - '{{ gitlab_internal_port }}'

- name: Disallow SSH on the default port
  ufw:
    rule: deny
    port: 22
    proto: tcp
    direction: in
