- name: Apply Common Config
  hosts: all
  become: true

  roles:
    - common


- name: Apply Docker Config
  hosts: 
    - servers
    - dmz
  #  - gitlab-runner
  become: true

  roles:
    - docker_host


- name: Apply Server Config
  hosts: servers
  become: true

  roles:
    - server

- name: Apply DMZ Config
  hosts: dmz
  become: true

  roles:
    - dmz


#- name: Apply Gitlab Server Config
#  hosts: gitlab-server
#  become: true
#
#  roles:
#    - gitlab_server