# Generated by Django 5.2.8 on 2025-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vpncert__key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='needs_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
